test = {
    'cod': '200', 'message': 0, 'cnt': 40, 'list':
        [
            {
                'dt': 1719230400,
                'main':
                    {
                     'temp': 297.02,
                     'feels_like': 296.79,
                     'temp_min': 297.02,
                     'temp_max': 297.02,
                     'pressure': 1016,
                     'sea_level': 1016,
                     'grnd_level': 983,
                     'humidity': 51,
                     'temp_kf': 0
                    },
                    'weather': [
                        {
                            'id': 801,
                            'main': 'Clouds',
                            'description': 'few clouds',
                            'icon': '02d'
                        }
                    ],
                'clouds': {'all': 11},
                'wind': {'speed': 4.46, 'deg': 336, 'gust': 4.85},
                'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'},
                'dt_txt': '2024-06-24 12:00:00'}
            ,






















            {'dt': 1719241200,
                                             'main': {'temp': 296.77,
                                                      'feels_like': 296.55,
                                                      'temp_min': 296.28,
                                                      'temp_max': 296.77,
                                                      'pressure': 1016,
                                                      'sea_level': 1016,
                                                      'grnd_level': 982,
                                                      'humidity': 52,
                                                      'temp_kf': 0.49},
                                             'weather': [{'id': 801,
                                                          'main': 'Clouds',
                                                          'description': 'few clouds',
                                                          'icon': '02d'}],
                                             'clouds': {'all': 19},
                                             'wind': {'speed': 3.61,
                                                      'deg': 332,
                                                      'gust': 5.23},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'd'},
                                             'dt_txt': '2024-06-24 15:00:00'},
         {'dt': 1719252000,
          'main': {'temp': 292.71, 'feels_like': 292.63,
                   'temp_min': 290.55, 'temp_max': 292.71,
                   'pressure': 1017, 'sea_level': 1017,
                   'grnd_level': 983, 'humidity': 73, 'temp_kf': 2.16},
          'weather': [
              {'id': 801, 'main': 'Clouds', 'description': 'few clouds',
               'icon': '02d'}], 'clouds': {'all': 20},
          'wind': {'speed': 1.97, 'deg': 343, 'gust': 2.52},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'},
          'dt_txt': '2024-06-24 18:00:00'}, {'dt': 1719262800,
                                             'main': {'temp': 287.59,
                                                      'feels_like': 287.47,
                                                      'temp_min': 287.59,
                                                      'temp_max': 287.59,
                                                      'pressure': 1019,
                                                      'sea_level': 1019,
                                                      'grnd_level': 985,
                                                      'humidity': 91,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 800,
                                                          'main': 'Clear',
                                                          'description': 'clear sky',
                                                          'icon': '01n'}],
                                             'clouds': {'all': 0},
                                             'wind': {'speed': 1.29,
                                                      'deg': 282,
                                                      'gust': 1.13},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'n'},
                                             'dt_txt': '2024-06-24 21:00:00'},
         {'dt': 1719273600,
          'main': {'temp': 286.45, 'feels_like': 286.26,
                   'temp_min': 286.45, 'temp_max': 286.45,
                   'pressure': 1019, 'sea_level': 1019,
                   'grnd_level': 985, 'humidity': 93, 'temp_kf': 0},
          'weather': [
              {'id': 800, 'main': 'Clear', 'description': 'clear sky',
               'icon': '01n'}], 'clouds': {'all': 0},
          'wind': {'speed': 0.93, 'deg': 296, 'gust': 0.88},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'},
          'dt_txt': '2024-06-25 00:00:00'}, {'dt': 1719284400,
                                             'main': {'temp': 286.13,
                                                      'feels_like': 285.96,
                                                      'temp_min': 286.13,
                                                      'temp_max': 286.13,
                                                      'pressure': 1019,
                                                      'sea_level': 1019,
                                                      'grnd_level': 985,
                                                      'humidity': 95,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 800,
                                                          'main': 'Clear',
                                                          'description': 'clear sky',
                                                          'icon': '01d'}],
                                             'clouds': {'all': 0},
                                             'wind': {'speed': 0.9,
                                                      'deg': 323,
                                                      'gust': 0.88},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'd'},
                                             'dt_txt': '2024-06-25 03:00:00'},
         {'dt': 1719295200,
          'main': {'temp': 291.14, 'feels_like': 291.11,
                   'temp_min': 291.14, 'temp_max': 291.14,
                   'pressure': 1019, 'sea_level': 1019,
                   'grnd_level': 985, 'humidity': 81, 'temp_kf': 0},
          'weather': [
              {'id': 800, 'main': 'Clear', 'description': 'clear sky',
               'icon': '01d'}], 'clouds': {'all': 4},
          'wind': {'speed': 1.11, 'deg': 351, 'gust': 1.18},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'},
          'dt_txt': '2024-06-25 06:00:00'}, {'dt': 1719306000,
                                             'main': {'temp': 294.6,
                                                      'feels_like': 294.47,
                                                      'temp_min': 294.6,
                                                      'temp_max': 294.6,
                                                      'pressure': 1019,
                                                      'sea_level': 1019,
                                                      'grnd_level': 985,
                                                      'humidity': 64,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 803,
                                                          'main': 'Clouds',
                                                          'description': 'broken clouds',
                                                          'icon': '04d'}],
                                             'clouds': {'all': 55},
                                             'wind': {'speed': 2.19,
                                                      'deg': 54,
                                                      'gust': 2.24},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'd'},
                                             'dt_txt': '2024-06-25 09:00:00'},
         {'dt': 1719316800,
          'main': {'temp': 294.76, 'feels_like': 294.62,
                   'temp_min': 294.76, 'temp_max': 294.76,
                   'pressure': 1018, 'sea_level': 1018,
                   'grnd_level': 985, 'humidity': 63, 'temp_kf': 0},
          'weather': [{'id': 803, 'main': 'Clouds',
                       'description': 'broken clouds', 'icon': '04d'}],
          'clouds': {'all': 69},
          'wind': {'speed': 2.78, 'deg': 81, 'gust': 2.93},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'},
          'dt_txt': '2024-06-25 12:00:00'}, {'dt': 1719327600,
                                             'main': {'temp': 296.84,
                                                      'feels_like': 296.75,
                                                      'temp_min': 296.84,
                                                      'temp_max': 296.84,
                                                      'pressure': 1017,
                                                      'sea_level': 1017,
                                                      'grnd_level': 984,
                                                      'humidity': 57,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 802,
                                                          'main': 'Clouds',
                                                          'description': 'scattered clouds',
                                                          'icon': '03d'}],
                                             'clouds': {'all': 27},
                                             'wind': {'speed': 3.67,
                                                      'deg': 98,
                                                      'gust': 3.84},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'd'},
                                             'dt_txt': '2024-06-25 15:00:00'},
         {'dt': 1719338400,
          'main': {'temp': 291.77, 'feels_like': 291.85,
                   'temp_min': 291.77, 'temp_max': 291.77,
                   'pressure': 1017, 'sea_level': 1017,
                   'grnd_level': 984, 'humidity': 83, 'temp_kf': 0},
          'weather': [
              {'id': 801, 'main': 'Clouds', 'description': 'few clouds',
               'icon': '02d'}], 'clouds': {'all': 18},
          'wind': {'speed': 2.56, 'deg': 92, 'gust': 3.77},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'},
          'dt_txt': '2024-06-25 18:00:00'}, {'dt': 1719349200,
                                             'main': {'temp': 289.08,
                                                      'feels_like': 289.13,
                                                      'temp_min': 289.08,
                                                      'temp_max': 289.08,
                                                      'pressure': 1018,
                                                      'sea_level': 1018,
                                                      'grnd_level': 984,
                                                      'humidity': 92,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 800,
                                                          'main': 'Clear',
                                                          'description': 'clear sky',
                                                          'icon': '01n'}],
                                             'clouds': {'all': 6},
                                             'wind': {'speed': 1.97,
                                                      'deg': 123,
                                                      'gust': 2.03},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'n'},
                                             'dt_txt': '2024-06-25 21:00:00'},
         {'dt': 1719360000,
          'main': {'temp': 288.06, 'feels_like': 288.06,
                   'temp_min': 288.06, 'temp_max': 288.06,
                   'pressure': 1017, 'sea_level': 1017,
                   'grnd_level': 984, 'humidity': 94, 'temp_kf': 0},
          'weather': [{'id': 802, 'main': 'Clouds',
                       'description': 'scattered clouds',
                       'icon': '03n'}], 'clouds': {'all': 33},
          'wind': {'speed': 2.14, 'deg': 131, 'gust': 2.86},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'},
          'dt_txt': '2024-06-26 00:00:00'}, {'dt': 1719370800,
                                             'main': {'temp': 287.46,
                                                      'feels_like': 287.4,
                                                      'temp_min': 287.46,
                                                      'temp_max': 287.46,
                                                      'pressure': 1017,
                                                      'sea_level': 1017,
                                                      'grnd_level': 983,
                                                      'humidity': 94,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 804,
                                                          'main': 'Clouds',
                                                          'description': 'overcast clouds',
                                                          'icon': '04d'}],
                                             'clouds': {'all': 86},
                                             'wind': {'speed': 2.2,
                                                      'deg': 126,
                                                      'gust': 4.05},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'd'},
                                             'dt_txt': '2024-06-26 03:00:00'},
         {'dt': 1719381600,
          'main': {'temp': 293.13, 'feels_like': 293.14,
                   'temp_min': 293.13, 'temp_max': 293.13,
                   'pressure': 1017, 'sea_level': 1017,
                   'grnd_level': 983, 'humidity': 75, 'temp_kf': 0},
          'weather': [{'id': 804, 'main': 'Clouds',
                       'description': 'overcast clouds', 'icon': '04d'}],
          'clouds': {'all': 85},
          'wind': {'speed': 4.7, 'deg': 128, 'gust': 7.62},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'},
          'dt_txt': '2024-06-26 06:00:00'}, {'dt': 1719392400,
                                             'main': {'temp': 297.55,
                                                      'feels_like': 297.56,
                                                      'temp_min': 297.55,
                                                      'temp_max': 297.55,
                                                      'pressure': 1016,
                                                      'sea_level': 1016,
                                                      'grnd_level': 983,
                                                      'humidity': 58,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 803,
                                                          'main': 'Clouds',
                                                          'description': 'broken clouds',
                                                          'icon': '04d'}],
                                             'clouds': {'all': 71},
                                             'wind': {'speed': 5.7,
                                                      'deg': 124,
                                                      'gust': 6.46},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'd'},
                                             'dt_txt': '2024-06-26 09:00:00'},
         {'dt': 1719403200,
          'main': {'temp': 299.67, 'feels_like': 299.67,
                   'temp_min': 299.67, 'temp_max': 299.67,
                   'pressure': 1015, 'sea_level': 1015,
                   'grnd_level': 981, 'humidity': 53, 'temp_kf': 0},
          'weather': [{'id': 802, 'main': 'Clouds',
                       'description': 'scattered clouds',
                       'icon': '03d'}], 'clouds': {'all': 43},
          'wind': {'speed': 5, 'deg': 115, 'gust': 5.13},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'},
          'dt_txt': '2024-06-26 12:00:00'}, {'dt': 1719414000,
                                             'main': {'temp': 299.29,
                                                      'feels_like': 299.29,
                                                      'temp_min': 299.29,
                                                      'temp_max': 299.29,
                                                      'pressure': 1014,
                                                      'sea_level': 1014,
                                                      'grnd_level': 981,
                                                      'humidity': 59,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 804,
                                                          'main': 'Clouds',
                                                          'description': 'overcast clouds',
                                                          'icon': '04d'}],
                                             'clouds': {'all': 100},
                                             'wind': {'speed': 4.04,
                                                      'deg': 112,
                                                      'gust': 5.05},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'd'},
                                             'dt_txt': '2024-06-26 15:00:00'},
         {'dt': 1719424800,
          'main': {'temp': 294.52, 'feels_like': 294.64,
                   'temp_min': 294.52, 'temp_max': 294.52,
                   'pressure': 1013, 'sea_level': 1013,
                   'grnd_level': 980, 'humidity': 74, 'temp_kf': 0},
          'weather': [{'id': 804, 'main': 'Clouds',
                       'description': 'overcast clouds', 'icon': '04d'}],
          'clouds': {'all': 100},
          'wind': {'speed': 4.55, 'deg': 102, 'gust': 11.27},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'},
          'dt_txt': '2024-06-26 18:00:00'}, {'dt': 1719435600,
                                             'main': {'temp': 291.37,
                                                      'feels_like': 291.23,
                                                      'temp_min': 291.37,
                                                      'temp_max': 291.37,
                                                      'pressure': 1014,
                                                      'sea_level': 1014,
                                                      'grnd_level': 980,
                                                      'humidity': 76,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 803,
                                                          'main': 'Clouds',
                                                          'description': 'broken clouds',
                                                          'icon': '04n'}],
                                             'clouds': {'all': 68},
                                             'wind': {'speed': 3.71,
                                                      'deg': 118,
                                                      'gust': 10.91},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'n'},
                                             'dt_txt': '2024-06-26 21:00:00'},
         {'dt': 1719446400,
          'main': {'temp': 289.53, 'feels_like': 289.29,
                   'temp_min': 289.53, 'temp_max': 289.53,
                   'pressure': 1013, 'sea_level': 1013,
                   'grnd_level': 980, 'humidity': 79, 'temp_kf': 0},
          'weather': [{'id': 803, 'main': 'Clouds',
                       'description': 'broken clouds', 'icon': '04n'}],
          'clouds': {'all': 52},
          'wind': {'speed': 4.24, 'deg': 117, 'gust': 12.61},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'},
          'dt_txt': '2024-06-27 00:00:00'}, {'dt': 1719457200,
                                             'main': {'temp': 288.94,
                                                      'feels_like': 288.66,
                                                      'temp_min': 288.94,
                                                      'temp_max': 288.94,
                                                      'pressure': 1013,
                                                      'sea_level': 1013,
                                                      'grnd_level': 980,
                                                      'humidity': 80,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 804,
                                                          'main': 'Clouds',
                                                          'description': 'overcast clouds',
                                                          'icon': '04d'}],
                                             'clouds': {'all': 95},
                                             'wind': {'speed': 3.46,
                                                      'deg': 116,
                                                      'gust': 10.78},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'd'},
                                             'dt_txt': '2024-06-27 03:00:00'},
         {'dt': 1719468000,
          'main': {'temp': 293.77, 'feels_like': 293.64,
                   'temp_min': 293.77, 'temp_max': 293.77,
                   'pressure': 1014, 'sea_level': 1014,
                   'grnd_level': 980, 'humidity': 67, 'temp_kf': 0},
          'weather': [{'id': 803, 'main': 'Clouds',
                       'description': 'broken clouds', 'icon': '04d'}],
          'clouds': {'all': 76},
          'wind': {'speed': 5.82, 'deg': 124, 'gust': 9.92},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'},
          'dt_txt': '2024-06-27 06:00:00'}, {'dt': 1719478800,
                                             'main': {'temp': 297.64,
                                                      'feels_like': 297.63,
                                                      'temp_min': 297.64,
                                                      'temp_max': 297.64,
                                                      'pressure': 1013,
                                                      'sea_level': 1013,
                                                      'grnd_level': 980,
                                                      'humidity': 57,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 804,
                                                          'main': 'Clouds',
                                                          'description': 'overcast clouds',
                                                          'icon': '04d'}],
                                             'clouds': {'all': 96},
                                             'wind': {'speed': 6.45,
                                                      'deg': 120,
                                                      'gust': 8.44},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'd'},
                                             'dt_txt': '2024-06-27 09:00:00'},
         {'dt': 1719489600,
          'main': {'temp': 299.81, 'feels_like': 299.81,
                   'temp_min': 299.81, 'temp_max': 299.81,
                   'pressure': 1012, 'sea_level': 1012,
                   'grnd_level': 979, 'humidity': 51, 'temp_kf': 0},
          'weather': [{'id': 804, 'main': 'Clouds',
                       'description': 'overcast clouds', 'icon': '04d'}],
          'clouds': {'all': 97},
          'wind': {'speed': 6.21, 'deg': 115, 'gust': 7.47},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'},
          'dt_txt': '2024-06-27 12:00:00'}, {'dt': 1719500400,
                                             'main': {'temp': 299.64,
                                                      'feels_like': 299.64,
                                                      'temp_min': 299.64,
                                                      'temp_max': 299.64,
                                                      'pressure': 1012,
                                                      'sea_level': 1012,
                                                      'grnd_level': 979,
                                                      'humidity': 56,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 804,
                                                          'main': 'Clouds',
                                                          'description': 'overcast clouds',
                                                          'icon': '04d'}],
                                             'clouds': {'all': 92},
                                             'wind': {'speed': 5.59,
                                                      'deg': 98,
                                                      'gust': 7.71},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'd'},
                                             'dt_txt': '2024-06-27 15:00:00'},
         {'dt': 1719511200,
          'main': {'temp': 294.91, 'feels_like': 294.97,
                   'temp_min': 294.91, 'temp_max': 294.91,
                   'pressure': 1012, 'sea_level': 1012,
                   'grnd_level': 979, 'humidity': 70, 'temp_kf': 0},
          'weather': [{'id': 804, 'main': 'Clouds',
                       'description': 'overcast clouds', 'icon': '04d'}],
          'clouds': {'all': 96},
          'wind': {'speed': 4.64, 'deg': 96, 'gust': 11.97},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'},
          'dt_txt': '2024-06-27 18:00:00'}, {'dt': 1719522000,
                                             'main': {'temp': 292.95,
                                                      'feels_like': 292.87,
                                                      'temp_min': 292.95,
                                                      'temp_max': 292.95,
                                                      'pressure': 1014,
                                                      'sea_level': 1014,
                                                      'grnd_level': 981,
                                                      'humidity': 72,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 804,
                                                          'main': 'Clouds',
                                                          'description': 'overcast clouds',
                                                          'icon': '04n'}],
                                             'clouds': {'all': 100},
                                             'wind': {'speed': 4.49,
                                                      'deg': 107,
                                                      'gust': 12.52},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'n'},
                                             'dt_txt': '2024-06-27 21:00:00'},
         {'dt': 1719532800,
          'main': {'temp': 290.79, 'feels_like': 290.75,
                   'temp_min': 290.79, 'temp_max': 290.79,
                   'pressure': 1014, 'sea_level': 1014,
                   'grnd_level': 981, 'humidity': 82, 'temp_kf': 0},
          'weather': [{'id': 804, 'main': 'Clouds',
                       'description': 'overcast clouds', 'icon': '04n'}],
          'clouds': {'all': 100},
          'wind': {'speed': 3.83, 'deg': 128, 'gust': 10.96},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'},
          'dt_txt': '2024-06-28 00:00:00'}, {'dt': 1719543600,
                                             'main': {'temp': 289.25,
                                                      'feels_like': 289.24,
                                                      'temp_min': 289.25,
                                                      'temp_max': 289.25,
                                                      'pressure': 1015,
                                                      'sea_level': 1015,
                                                      'grnd_level': 981,
                                                      'humidity': 89,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 803,
                                                          'main': 'Clouds',
                                                          'description': 'broken clouds',
                                                          'icon': '04d'}],
                                             'clouds': {'all': 67},
                                             'wind': {'speed': 2.55,
                                                      'deg': 130,
                                                      'gust': 8.47},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'd'},
                                             'dt_txt': '2024-06-28 03:00:00'},
         {'dt': 1719554400,
          'main': {'temp': 294.35, 'feels_like': 294.35,
                   'temp_min': 294.35, 'temp_max': 294.35,
                   'pressure': 1015, 'sea_level': 1015,
                   'grnd_level': 982, 'humidity': 70, 'temp_kf': 0},
          'weather': [{'id': 803, 'main': 'Clouds',
                       'description': 'broken clouds', 'icon': '04d'}],
          'clouds': {'all': 80},
          'wind': {'speed': 5.08, 'deg': 129, 'gust': 8.14},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'},
          'dt_txt': '2024-06-28 06:00:00'}, {'dt': 1719565200,
                                             'main': {'temp': 298.68,
                                                      'feels_like': 298.75,
                                                      'temp_min': 298.68,
                                                      'temp_max': 298.68,
                                                      'pressure': 1015,
                                                      'sea_level': 1015,
                                                      'grnd_level': 982,
                                                      'humidity': 56,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 804,
                                                          'main': 'Clouds',
                                                          'description': 'overcast clouds',
                                                          'icon': '04d'}],
                                             'clouds': {'all': 92},
                                             'wind': {'speed': 5.34,
                                                      'deg': 121,
                                                      'gust': 6.11},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'd'},
                                             'dt_txt': '2024-06-28 09:00:00'},
         {'dt': 1719576000,
          'main': {'temp': 300.97, 'feels_like': 301.32,
                   'temp_min': 300.97, 'temp_max': 300.97,
                   'pressure': 1015, 'sea_level': 1015,
                   'grnd_level': 982, 'humidity': 49, 'temp_kf': 0},
          'weather': [{'id': 804, 'main': 'Clouds',
                       'description': 'overcast clouds', 'icon': '04d'}],
          'clouds': {'all': 87},
          'wind': {'speed': 4.72, 'deg': 115, 'gust': 4.79},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'},
          'dt_txt': '2024-06-28 12:00:00'}, {'dt': 1719586800,
                                             'main': {'temp': 300.72,
                                                      'feels_like': 301.06,
                                                      'temp_min': 300.72,
                                                      'temp_max': 300.72,
                                                      'pressure': 1015,
                                                      'sea_level': 1015,
                                                      'grnd_level': 982,
                                                      'humidity': 49,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 802,
                                                          'main': 'Clouds',
                                                          'description': 'scattered clouds',
                                                          'icon': '03d'}],
                                             'clouds': {'all': 31},
                                             'wind': {'speed': 4.21,
                                                      'deg': 112,
                                                      'gust': 4.25},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'd'},
                                             'dt_txt': '2024-06-28 15:00:00'},
         {'dt': 1719597600,
          'main': {'temp': 295.14, 'feels_like': 295.35,
                   'temp_min': 295.14, 'temp_max': 295.14,
                   'pressure': 1016, 'sea_level': 1016,
                   'grnd_level': 982, 'humidity': 75, 'temp_kf': 0},
          'weather': [{'id': 802, 'main': 'Clouds',
                       'description': 'scattered clouds',
                       'icon': '03d'}], 'clouds': {'all': 41},
          'wind': {'speed': 2.97, 'deg': 106, 'gust': 5.8},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'},
          'dt_txt': '2024-06-28 18:00:00'}, {'dt': 1719608400,
                                             'main': {'temp': 291.75,
                                                      'feels_like': 291.65,
                                                      'temp_min': 291.75,
                                                      'temp_max': 291.75,
                                                      'pressure': 1017,
                                                      'sea_level': 1017,
                                                      'grnd_level': 983,
                                                      'humidity': 76,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 802,
                                                          'main': 'Clouds',
                                                          'description': 'scattered clouds',
                                                          'icon': '03n'}],
                                             'clouds': {'all': 28},
                                             'wind': {'speed': 2.17,
                                                      'deg': 147,
                                                      'gust': 2.39},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'n'},
                                             'dt_txt': '2024-06-28 21:00:00'},
         {'dt': 1719619200,
          'main': {'temp': 290.28, 'feels_like': 290.19,
                   'temp_min': 290.28, 'temp_max': 290.28,
                   'pressure': 1017, 'sea_level': 1017,
                   'grnd_level': 983, 'humidity': 82, 'temp_kf': 0},
          'weather': [{'id': 802, 'main': 'Clouds',
                       'description': 'scattered clouds',
                       'icon': '03n'}], 'clouds': {'all': 25},
          'wind': {'speed': 1.88, 'deg': 140, 'gust': 1.91},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'},
          'dt_txt': '2024-06-29 00:00:00'}, {'dt': 1719630000,
                                             'main': {'temp': 290.29,
                                                      'feels_like': 290.28,
                                                      'temp_min': 290.29,
                                                      'temp_max': 290.29,
                                                      'pressure': 1017,
                                                      'sea_level': 1017,
                                                      'grnd_level': 983,
                                                      'humidity': 85,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 803,
                                                          'main': 'Clouds',
                                                          'description': 'broken clouds',
                                                          'icon': '04d'}],
                                             'clouds': {'all': 77},
                                             'wind': {'speed': 2.02,
                                                      'deg': 136,
                                                      'gust': 2.61},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'd'},
                                             'dt_txt': '2024-06-29 03:00:00'},
         {'dt': 1719640800,
          'main': {'temp': 295, 'feels_like': 295.02, 'temp_min': 295,
                   'temp_max': 295, 'pressure': 1017, 'sea_level': 1017,
                   'grnd_level': 983, 'humidity': 68, 'temp_kf': 0},
          'weather': [{'id': 804, 'main': 'Clouds',
                       'description': 'overcast clouds', 'icon': '04d'}],
          'clouds': {'all': 90},
          'wind': {'speed': 3.98, 'deg': 133, 'gust': 5.56},
          'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'},
          'dt_txt': '2024-06-29 06:00:00'}, {'dt': 1719651600,
                                             'main': {'temp': 300.1,
                                                      'feels_like': 300.58,
                                                      'temp_min': 300.1,
                                                      'temp_max': 300.1,
                                                      'pressure': 1016,
                                                      'sea_level': 1016,
                                                      'grnd_level': 983,
                                                      'humidity': 51,
                                                      'temp_kf': 0},
                                             'weather': [{'id': 801,
                                                          'main': 'Clouds',
                                                          'description': 'few clouds',
                                                          'icon': '02d'}],
                                             'clouds': {'all': 18},
                                             'wind': {'speed': 4.55,
                                                      'deg': 134,
                                                      'gust': 4.78},
                                             'visibility': 10000,
                                             'pop': 0,
                                             'sys': {'pod': 'd'},
                                             'dt_txt': '2024-06-29 09:00:00'}
         ],
    'city': {'id': 707471, 'name': 'Ivano-Frankivsk', 'coord': {'lat': 48.9225, 'lon': 24.7103}, 'country': 'UA',
             'population': 204200, 'timezone': 10800, 'sunrise': 1719195485, 'sunset': 1719253744}
}
